stan-core:
  stanPath: .stan
  imports:
    entity-client-dynamodb:
      - ../entity-client-dynamodb/.stan/interop/smoz/**
      - ../entity-client-dynamodb/guides/cli/**
      - ../entity-client-dynamodb/guides/entityclient-and-crud.md
      - ../entity-client-dynamodb/guides/querying-with-querybuilder.md
      - ../entity-client-dynamodb/guides/tables-and-definition.md
      - ../entity-client-dynamodb/src/EntityClient/EntityClient.test.ts
    entity-manager-demo:
      - ../entity-manager-demo/src/entity-manager/entityClient.ts
      - ../entity-manager-demo/src/entity-manager/entityManager.ts
      - ../entity-manager-demo/src/entity-manager/User.ts
      - ../entity-manager-demo/src/handlers/user/**
    get-dotenv:
      - ../get-dotenv/.stan/interop/smoz/**
      - ../get-dotenv/guides/config.md
      - ../get-dotenv/guides/plugins/index.md
  includes:
    - templates/**
  excludes:
    - '**/.tsbuild/**'
    - '**/generated/**'
    - '**/node_modules/**'
    - '**/*.tsbuildinfo'
    - CHANGELOG.md
    - docs
    - package-lock.json
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint: npm run lint:fix
    openapi: npm run openapi
    test: npm run test -- --no-color
    build: cross-env NO_COLOR=1 npm run build
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    knip:
      script: npm run knip
      warnPattern: hints
    package: npm run package
