stan-core:
  stanPath: .stan
  imports:
    '@karmaniverous/entity-client-dynamodb':
      - ../entity-client-dynamodb/.stan/interop/smoz/**
      - ../entity-client-dynamodb/guides/stan-assistant-guide.md
    '@karmaniverous/entity-manager':
      - ../entity-manager/.stan/interop/smoz/**
      - ../entity-manager/guides/stan-assistant-guide.md
    '@karmaniverous/entity-manager-demo':
      - ../entity-manager-demo/.stan/interop/smoz/**
    '@karmaniverous/get-dotenv':
      - ../get-dotenv/.stan/interop/smoz/**
      - ../get-dotenv/guides/stan-assistant-guide.md
  includes:
    - templates/**
  excludes:
    - '**/.tsbuild/**'
    - '**/generated/**'
    - '**/node_modules/**'
    - '**/*.tsbuildinfo'
    - CHANGELOG.md
    - docs
    - package-lock.json
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    build: cross-env NO_COLOR=1 npm run build
    typecheck: npm run typecheck -- --noErrorTruncation
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    openapi: npm run openapi
    test: npm run test -- --no-color
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    knip:
      script: npm run knip
      warnPattern: hints
    package: npm run package
